export const agentDirectoryData = [
  {
    id: 'priya-sharma',
    name: 'Priya Sharma',
    role: 'Verified Agent',
    city: 'Mumbai',
    avatar: 'https://i.pravatar.cc/150?img=32',
    experience: '8 years',
    specialties: ['Luxury homes', 'Sea-view apartments', 'Buyer advisory'],
    languages: ['English', 'Hindi', 'Marathi'],
    responseRate: '96%',
    averageRating: 4.9,
    totalDeals: 124,
    activeListings: 8,
    bio: 'Priya helps buyers compare premium Mumbai and Goa properties with a focus on pricing confidence, lifestyle fit, and smooth owner conversations.',
    trustLevel: 'NestIQ trusted contact',
    phone: '+91 90000 10002',
    email: 'priya.agent@nestiq.com',
    reviewHighlights: ['Clear communication and fast follow-up.', 'Helped us compare homes without pressure.', 'Strong local context for premium apartments.'],
  },
  {
    id: 'rohan-kapoor',
    name: 'Rohan Kapoor',
    role: 'Seller Specialist',
    city: 'Pune',
    avatar: 'https://i.pravatar.cc/150?img=15',
    experience: '6 years',
    specialties: ['Seller listings', 'IT corridor homes', 'Pricing preparation'],
    languages: ['English', 'Hindi', 'Marathi'],
    responseRate: '91%',
    averageRating: 4.8,
    totalDeals: 87,
    activeListings: 5,
    bio: 'Rohan works with sellers and buyers across Pune and Hyderabad, helping listings become more complete, comparable, and easier to evaluate.',
    trustLevel: 'NestIQ seller contact',
    phone: '+91 90000 10003',
    email: 'rohan.seller@nestiq.com',
    reviewHighlights: ['Prepared our listing clearly.', 'Good advice on photos and description quality.', 'Responsive during visit scheduling.'],
  },
  {
    id: 'neha-iyer',
    name: 'Neha Iyer',
    role: 'Verified Agent',
    city: 'Gurgaon',
    avatar: 'https://i.pravatar.cc/150?img=47',
    experience: '9 years',
    specialties: ['Luxury towers', 'NCR relocation', 'Investment shortlists'],
    languages: ['English', 'Hindi', 'Tamil'],
    responseRate: '94%',
    averageRating: 4.9,
    totalDeals: 142,
    activeListings: 10,
    bio: 'Neha supports buyers and investors evaluating Gurgaon, Delhi, and Chennai homes with a structured shortlist-first approach.',
    trustLevel: 'NestIQ trusted contact',
    phone: '+91 90000 10004',
    email: 'neha.agent@nestiq.com',
    reviewHighlights: ['Excellent Gurgaon locality knowledge.', 'Helped us understand tradeoffs clearly.', 'Very organized follow-up.'],
  },
  {
    id: 'ananya-rao',
    name: 'Ananya Rao',
    role: 'Rental Advisor',
    city: 'Bangalore',
    avatar: 'https://i.pravatar.cc/150?img=44',
    experience: '5 years',
    specialties: ['Rentals', 'PG / room search', 'Tech corridor homes'],
    languages: ['English', 'Hindi', 'Kannada'],
    responseRate: '93%',
    averageRating: 4.7,
    totalDeals: 64,
    activeListings: 6,
    bio: 'Ananya helps renters and first-time buyers compare Bangalore neighborhoods around commute, amenities, and lifestyle fit.',
    trustLevel: 'NestIQ demo contact',
    phone: '+91 90000 10005',
    email: 'ananya.agent@nestiq.com',
    reviewHighlights: ['Great rental shortlist.', 'Understood commute needs quickly.', 'Helpful with furnished-home comparisons.'],
  },
]

export const getAgentById = (agentId) => agentDirectoryData.find((agent) => agent.id === agentId)
