export const cityLandingData = {
  mumbai: {
    name: 'Mumbai',
    tagline: 'Sea-view apartments, luxury towers, and central business access.',
    averagePrice: 'Rs. 4.2 Cr',
    averagePricePerSqft: 'Rs. 31,500',
    demandLevel: 'Very high',
    investmentScore: 91,
    lifestyleScore: 88,
    topLocalities: ['Bandra West', 'Powai', 'Worli', 'Andheri West', 'Lower Parel'],
    popularPropertyTypes: [
      ['Apartments', 68],
      ['Luxury homes', 18],
      ['Builder floors', 9],
      ['Villas', 5],
    ],
    popularSearches: [
      { label: 'Sea-view homes in Mumbai', params: { city: 'Mumbai', q: 'sea view' } },
      { label: '3 BHK in Bandra', params: { city: 'Mumbai', bhk: '3', q: 'Bandra' } },
      { label: 'Homes under Rs. 5Cr', params: { city: 'Mumbai', maxPrice: '50000000' } },
    ],
    summary: 'Mumbai is a high-demand metro market shaped by employment hubs, limited land supply, and strong lifestyle-driven neighborhoods.',
  },
  pune: {
    name: 'Pune',
    tagline: 'IT corridors, gated communities, and family-friendly growth markets.',
    averagePrice: 'Rs. 95 L',
    averagePricePerSqft: 'Rs. 9,500',
    demandLevel: 'High',
    investmentScore: 84,
    lifestyleScore: 86,
    topLocalities: ['Hinjewadi', 'Kharadi', 'Baner', 'Wakad', 'Viman Nagar'],
    popularPropertyTypes: [['Apartments', 72], ['Villas', 10], ['Plots', 8], ['PG / rentals', 10]],
    popularSearches: [
      { label: '2 BHK in Hinjewadi', params: { city: 'Pune', bhk: '2', q: 'Hinjewadi' } },
      { label: 'Flats under Rs. 1Cr', params: { city: 'Pune', type: 'Apartment', maxPrice: '10000000' } },
      { label: 'Homes near IT parks', params: { city: 'Pune', q: 'IT park' } },
    ],
    summary: 'Pune combines technology employment, universities, and livable neighborhoods, making it a balanced buyer and rental market.',
  },
  goa: {
    name: 'Goa',
    tagline: 'Beachside villas, boutique apartments, and lifestyle-led investments.',
    averagePrice: 'Rs. 2.6 Cr',
    averagePricePerSqft: 'Rs. 12,500',
    demandLevel: 'High',
    investmentScore: 87,
    lifestyleScore: 94,
    topLocalities: ['Assagao', 'Anjuna', 'Siolim', 'Panaji', 'Candolim'],
    popularPropertyTypes: [['Villas', 44], ['Apartments', 30], ['Plots', 16], ['Holiday homes', 10]],
    popularSearches: [
      { label: 'Villas in North Goa', params: { city: 'Goa', type: 'Villa', q: 'North Goa' } },
      { label: 'Pool homes in Goa', params: { city: 'Goa', amenities: 'Pool' } },
      { label: 'Sea-view homes', params: { city: 'Goa', q: 'sea view' } },
    ],
    summary: 'Goa is a lifestyle-first property market with strong interest in villas, second homes, and hospitality-adjacent neighborhoods.',
  },
  bangalore: {
    name: 'Bangalore',
    tagline: 'Tech-driven neighborhoods, villas, and premium apartment communities.',
    averagePrice: 'Rs. 1.55 Cr',
    averagePricePerSqft: 'Rs. 12,000',
    demandLevel: 'Very high',
    investmentScore: 89,
    lifestyleScore: 87,
    topLocalities: ['Whitefield', 'Sarjapur Road', 'Indiranagar', 'Hebbal', 'Electronic City'],
    popularPropertyTypes: [['Apartments', 64], ['Villas', 20], ['Plots', 8], ['Rentals', 8]],
    popularSearches: [
      { label: 'Villas near Whitefield', params: { city: 'Bangalore', type: 'Villa', q: 'Whitefield' } },
      { label: '3 BHK apartments', params: { city: 'Bangalore', type: 'Apartment', bhk: '3' } },
      { label: 'Homes with gym', params: { city: 'Bangalore', amenities: 'Gym' } },
    ],
    summary: 'Bangalore demand is anchored by technology employment, established residential corridors, and steady upgrade demand.',
  },
  delhi: {
    name: 'Delhi',
    tagline: 'Builder floors, premium colonies, and established urban infrastructure.',
    averagePrice: 'Rs. 3.4 Cr',
    averagePricePerSqft: 'Rs. 16,000',
    demandLevel: 'High',
    investmentScore: 82,
    lifestyleScore: 84,
    topLocalities: ['Greater Kailash', 'Saket', 'Dwarka', 'Rohini', 'Vasant Kunj'],
    popularPropertyTypes: [['Builder floors', 45], ['Apartments', 35], ['Houses', 12], ['Plots', 8]],
    popularSearches: [
      { label: '4 BHK in South Delhi', params: { city: 'Delhi', bhk: '4', q: 'South Delhi' } },
      { label: 'Builder floors', params: { city: 'Delhi', type: 'House' } },
      { label: 'Homes near metro', params: { city: 'Delhi', q: 'metro' } },
    ],
    summary: 'Delhi offers established localities, builder-floor inventory, and strong connectivity-led property demand.',
  },
  hyderabad: {
    name: 'Hyderabad',
    tagline: 'Financial District access, high-rise communities, and growth corridors.',
    averagePrice: 'Rs. 1.25 Cr',
    averagePricePerSqft: 'Rs. 10,500',
    demandLevel: 'High',
    investmentScore: 86,
    lifestyleScore: 85,
    topLocalities: ['Gachibowli', 'Kondapur', 'HITEC City', 'Kokapet', 'Madhapur'],
    popularPropertyTypes: [['Apartments', 70], ['Villas', 14], ['Plots', 10], ['Rentals', 6]],
    popularSearches: [
      { label: '3 BHK in Gachibowli', params: { city: 'Hyderabad', bhk: '3', q: 'Gachibowli' } },
      { label: 'Homes near Financial District', params: { city: 'Hyderabad', q: 'Financial District' } },
      { label: 'High-rise apartments', params: { city: 'Hyderabad', type: 'Apartment' } },
    ],
    summary: 'Hyderabad continues to attract buyers around business districts, infrastructure expansion, and large-format communities.',
  },
  nashik: {
    name: 'Nashik',
    tagline: 'Plots, bungalow communities, and emerging residential corridors.',
    averagePrice: 'Rs. 58 L',
    averagePricePerSqft: 'Rs. 5,200',
    demandLevel: 'Moderate',
    investmentScore: 76,
    lifestyleScore: 79,
    topLocalities: ['Gangapur Road', 'College Road', 'Pathardi Phata', 'Indira Nagar', 'Makhmalabad'],
    popularPropertyTypes: [['Plots', 36], ['Apartments', 34], ['Houses', 20], ['Villas', 10]],
    popularSearches: [
      { label: 'Plots near Gangapur Road', params: { city: 'Nashik', type: 'Plot', q: 'Gangapur Road' } },
      { label: 'Affordable apartments', params: { city: 'Nashik', type: 'Apartment', maxPrice: '7500000' } },
      { label: 'Bungalow-ready homes', params: { city: 'Nashik', type: 'House' } },
    ],
    summary: 'Nashik is an accessible residential market with interest in plots, independent homes, and lower-ticket apartments.',
  },
  gurgaon: {
    name: 'Gurgaon',
    tagline: 'Luxury towers, business access, and premium gated communities.',
    averagePrice: 'Rs. 2.4 Cr',
    averagePricePerSqft: 'Rs. 14,500',
    demandLevel: 'Very high',
    investmentScore: 88,
    lifestyleScore: 86,
    topLocalities: ['Golf Course Road', 'DLF Phase 5', 'Sohna Road', 'Sector 54', 'New Gurgaon'],
    popularPropertyTypes: [['Apartments', 58], ['Luxury homes', 24], ['Villas', 10], ['Builder floors', 8]],
    popularSearches: [
      { label: 'Luxury homes in Gurgaon', params: { city: 'Gurgaon', q: 'luxury' } },
      { label: 'Golf Course Road homes', params: { city: 'Gurgaon', q: 'Golf Course Road' } },
      { label: '3 BHK apartments', params: { city: 'Gurgaon', bhk: '3', type: 'Apartment' } },
    ],
    summary: 'Gurgaon is a premium NCR market with strong corporate demand, luxury inventory, and high-rise gated communities.',
  },
  chennai: {
    name: 'Chennai',
    tagline: 'Mature neighborhoods, coastal access, and family-oriented apartments.',
    averagePrice: 'Rs. 1.35 Cr',
    averagePricePerSqft: 'Rs. 9,800',
    demandLevel: 'High',
    investmentScore: 81,
    lifestyleScore: 84,
    topLocalities: ['Adyar', 'OMR', 'Anna Nagar', 'Velachery', 'ECR'],
    popularPropertyTypes: [['Apartments', 66], ['Houses', 16], ['Villas', 10], ['Plots', 8]],
    popularSearches: [
      { label: 'Homes in Adyar', params: { city: 'Chennai', q: 'Adyar' } },
      { label: 'Apartments near OMR', params: { city: 'Chennai', type: 'Apartment', q: 'OMR' } },
      { label: 'Beach access homes', params: { city: 'Chennai', q: 'beach' } },
    ],
    summary: 'Chennai demand is supported by mature residential neighborhoods, education, healthcare, and coastal lifestyle corridors.',
  },
  kolkata: {
    name: 'Kolkata',
    tagline: 'Affordable apartments, established neighborhoods, and transit-led demand.',
    averagePrice: 'Rs. 72 L',
    averagePricePerSqft: 'Rs. 7,500',
    demandLevel: 'Moderate',
    investmentScore: 75,
    lifestyleScore: 82,
    topLocalities: ['Salt Lake', 'New Town', 'Rajarhat', 'Ballygunge', 'Tollygunge'],
    popularPropertyTypes: [['Apartments', 74], ['Houses', 12], ['Plots', 8], ['Rentals', 6]],
    popularSearches: [
      { label: 'Apartments in Salt Lake', params: { city: 'Kolkata', type: 'Apartment', q: 'Salt Lake' } },
      { label: 'Affordable 2 BHK', params: { city: 'Kolkata', bhk: '2', maxPrice: '8000000' } },
      { label: 'Homes near Sector V', params: { city: 'Kolkata', q: 'Sector V' } },
    ],
    summary: 'Kolkata offers comparatively accessible pricing with demand around IT hubs, established localities, and improving connectivity.',
  },
}

export const citySlugList = Object.keys(cityLandingData)

export const getCityLanding = (slug) => cityLandingData[String(slug || '').toLowerCase()]
